/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package routine;

/**
 *
 * @author A S U S
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import jdk.nashorn.internal.runtime.regexp.joni.Config;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.EventListener;
import javax.swing.table.*;
import java.lang.NullPointerException;
import static javafx.application.Platform.exit;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu Menu;
    public mj1 mj1;
    public mj2 mj2;
    public mj3 mj3;
    public mj4 mj4;
    public mj5 mj5;
    public mj6 mj6;
    public mj7 mj7;
    public mj8 mj8;
    public mj9 mj9;
    public mj10 mj10;
    public mj11 mj11;
    public mj12 mj12;
    public mj13 mj13;
    public mj14 mj14;
    public mj15 mj15;
    public mj16 mj16;
    public mj17 mj17;
    public mj18 mj18;
    public mj19 mj19;
    public mj20 mj20;
    public mj21 mj21;
    
    private Connection conm;
    private Statement sttm;
    private Connection conk;
    private Statement sttk;
    
    public Menu() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conm = DriverManager.getConnection("jdbc:mysql://localhost:3306/routine" , "root" , "");
            sttm = conm.createStatement();
            JOptionPane.showMessageDialog(null,"Koneksi Aktif");
            statm.setText("AKTIF");
            statm.setForeground(Color.green);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statm.setText("TIDAK AKTIF");
            statm.setForeground(Color.red);
            
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tmj1 = new javax.swing.JButton();
        tmj2 = new javax.swing.JButton();
        tmj3 = new javax.swing.JButton();
        tmj4 = new javax.swing.JButton();
        tmj5 = new javax.swing.JButton();
        tmj6 = new javax.swing.JButton();
        tmj7 = new javax.swing.JButton();
        tmj15 = new javax.swing.JButton();
        tmj8 = new javax.swing.JButton();
        tmj9 = new javax.swing.JButton();
        tmj16 = new javax.swing.JButton();
        tmj10 = new javax.swing.JButton();
        tmj17 = new javax.swing.JButton();
        tmj11 = new javax.swing.JButton();
        tmj12 = new javax.swing.JButton();
        tmj13 = new javax.swing.JButton();
        tmj14 = new javax.swing.JButton();
        tmj18 = new javax.swing.JButton();
        tmj19 = new javax.swing.JButton();
        tmj20 = new javax.swing.JButton();
        tmj21 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        statm = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/routine/menu.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        tmj1.setBackground(new java.awt.Color(255, 153, 0));
        tmj1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj1.setText("Meja 1");
        tmj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj1ActionPerformed(evt);
            }
        });

        tmj2.setBackground(new java.awt.Color(255, 153, 0));
        tmj2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj2.setText("Meja 2");
        tmj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj2ActionPerformed(evt);
            }
        });

        tmj3.setBackground(new java.awt.Color(255, 153, 0));
        tmj3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj3.setText("Meja 3");
        tmj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj3ActionPerformed(evt);
            }
        });

        tmj4.setBackground(new java.awt.Color(255, 153, 0));
        tmj4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj4.setText("Meja 4");
        tmj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj4ActionPerformed(evt);
            }
        });

        tmj5.setBackground(new java.awt.Color(255, 153, 0));
        tmj5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj5.setText("Meja 5");
        tmj5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj5ActionPerformed(evt);
            }
        });

        tmj6.setBackground(new java.awt.Color(255, 153, 0));
        tmj6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj6.setText("Meja 6");
        tmj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj6ActionPerformed(evt);
            }
        });

        tmj7.setBackground(new java.awt.Color(255, 153, 0));
        tmj7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj7.setText("Meja 7");
        tmj7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj7ActionPerformed(evt);
            }
        });

        tmj15.setBackground(new java.awt.Color(255, 153, 0));
        tmj15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj15.setText("Meja 15");
        tmj15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj15ActionPerformed(evt);
            }
        });

        tmj8.setBackground(new java.awt.Color(255, 153, 0));
        tmj8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj8.setText("Meja 8");
        tmj8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj8ActionPerformed(evt);
            }
        });

        tmj9.setBackground(new java.awt.Color(255, 153, 0));
        tmj9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj9.setText("Meja 9");
        tmj9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj9ActionPerformed(evt);
            }
        });

        tmj16.setBackground(new java.awt.Color(255, 153, 0));
        tmj16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj16.setText("Meja 16");
        tmj16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj16ActionPerformed(evt);
            }
        });

        tmj10.setBackground(new java.awt.Color(255, 153, 0));
        tmj10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj10.setText("Meja 10");
        tmj10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj10ActionPerformed(evt);
            }
        });

        tmj17.setBackground(new java.awt.Color(255, 153, 0));
        tmj17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj17.setText("Meja 17");
        tmj17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj17ActionPerformed(evt);
            }
        });

        tmj11.setBackground(new java.awt.Color(255, 153, 0));
        tmj11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj11.setText("Meja 11");
        tmj11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj11ActionPerformed(evt);
            }
        });

        tmj12.setBackground(new java.awt.Color(255, 153, 0));
        tmj12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj12.setText("Meja 12");
        tmj12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj12ActionPerformed(evt);
            }
        });

        tmj13.setBackground(new java.awt.Color(255, 153, 0));
        tmj13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj13.setText("Meja 13");
        tmj13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj13ActionPerformed(evt);
            }
        });

        tmj14.setBackground(new java.awt.Color(255, 153, 0));
        tmj14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj14.setText("Meja 14");
        tmj14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj14ActionPerformed(evt);
            }
        });

        tmj18.setBackground(new java.awt.Color(255, 153, 0));
        tmj18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj18.setText("Meja 18");
        tmj18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj18ActionPerformed(evt);
            }
        });

        tmj19.setBackground(new java.awt.Color(255, 153, 0));
        tmj19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj19.setText("Meja 19");
        tmj19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj19ActionPerformed(evt);
            }
        });

        tmj20.setBackground(new java.awt.Color(255, 153, 0));
        tmj20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj20.setText("Meja 20");
        tmj20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj20ActionPerformed(evt);
            }
        });

        tmj21.setBackground(new java.awt.Color(255, 153, 0));
        tmj21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tmj21.setText("Meja 21");
        tmj21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmj21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tmj8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tmj2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tmj9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tmj16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tmj21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmj1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmj8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmj15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmj21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Status :");

        statm.setForeground(new java.awt.Color(255, 255, 255));
        statm.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(statm)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(statm))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Data Penjualan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem3.setText("Keluar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator4);

        jMenuItem5.setText("Tentang");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Setting");
        jMenu2.add(jSeparator3);

        jMenuItem4.setText("Koneksi DBS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int Pilih = JOptionPane.showConfirmDialog (this,"Apakah Anda Ingin Keluar ?","Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
        if(Pilih == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
        
   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tmj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj1ActionPerformed
        // TODO add your handling code here:
        mj1 m1 = new mj1();
        m1.setVisible(true);
        
        
    }//GEN-LAST:event_tmj1ActionPerformed

    private void tmj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj2ActionPerformed
        // TODO add your handling code here:
        mj2 m2 = new mj2();
        m2.setVisible(true);
    }//GEN-LAST:event_tmj2ActionPerformed

    private void tmj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj3ActionPerformed
        // TODO add your handling code here:
        mj3 m3 = new mj3();
        m3.setVisible(true);
    }//GEN-LAST:event_tmj3ActionPerformed

    private void tmj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj4ActionPerformed
        // TODO add your handling code here:
        mj4 m4 = new mj4();
        m4.setVisible(true);
    }//GEN-LAST:event_tmj4ActionPerformed

    private void tmj5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj5ActionPerformed
        // TODO add your handling code here:
        mj5 m5 = new mj5();
        m5.setVisible(true);
    }//GEN-LAST:event_tmj5ActionPerformed

    private void tmj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj6ActionPerformed
        // TODO add your handling code here:
        mj6 m6 = new mj6();
        m6.setVisible(true);
    }//GEN-LAST:event_tmj6ActionPerformed

    private void tmj7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj7ActionPerformed
        // TODO add your handling code here:
        mj7 m7 = new mj7();
        m7.setVisible(true);
    }//GEN-LAST:event_tmj7ActionPerformed

    private void tmj8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj8ActionPerformed
        // TODO add your handling code here:
        mj8 m8 = new mj8();
        m8.setVisible(true);
    }//GEN-LAST:event_tmj8ActionPerformed

    private void tmj9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj9ActionPerformed
        // TODO add your handling code here:
        mj9 m9 = new mj9();
        m9.setVisible(true);
    }//GEN-LAST:event_tmj9ActionPerformed

    private void tmj10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj10ActionPerformed
        // TODO add your handling code here:
        mj10 m10 = new mj10();
        m10.setVisible(true);
    }//GEN-LAST:event_tmj10ActionPerformed

    private void tmj11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj11ActionPerformed
        // TODO add your handling code here:
        mj11 m11 = new mj11();
        m11.setVisible(true);
    }//GEN-LAST:event_tmj11ActionPerformed

    private void tmj12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj12ActionPerformed
        // TODO add your handling code here:
        mj12 m12 = new mj12();
        m12.setVisible(true);
    }//GEN-LAST:event_tmj12ActionPerformed

    private void tmj13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj13ActionPerformed
        // TODO add your handling code here:
        mj13 m13 = new mj13();
        m13.setVisible(true);
    }//GEN-LAST:event_tmj13ActionPerformed

    private void tmj14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj14ActionPerformed
        // TODO add your handling code here:
        mj14 m14 = new mj14();
        m14.setVisible(true);
    }//GEN-LAST:event_tmj14ActionPerformed

    private void tmj15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj15ActionPerformed
        // TODO add your handling code here:
        mj15 m15 = new mj15();
        m15.setVisible(true);
    }//GEN-LAST:event_tmj15ActionPerformed

    private void tmj16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj16ActionPerformed
        // TODO add your handling code here:
        mj16 m16 = new mj16();
        m16.setVisible(true);
    }//GEN-LAST:event_tmj16ActionPerformed

    private void tmj17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj17ActionPerformed
        // TODO add your handling code here:
        mj17 m17 = new mj17();
        m17.setVisible(true);
    }//GEN-LAST:event_tmj17ActionPerformed

    private void tmj18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj18ActionPerformed
        // TODO add your handling code here:
        mj18 m18 = new mj18();
        m18.setVisible(true);
    }//GEN-LAST:event_tmj18ActionPerformed

    private void tmj19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj19ActionPerformed
        // TODO add your handling code here:
        mj19 m19 = new mj19();
        m19.setVisible(true);
    }//GEN-LAST:event_tmj19ActionPerformed

    private void tmj20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj20ActionPerformed
        // TODO add your handling code here:
        mj20 m20 = new mj20();
        m20.setVisible(true);
    }//GEN-LAST:event_tmj20ActionPerformed

    private void tmj21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmj21ActionPerformed
        // TODO add your handling code here:
         mj21 m21 = new mj21();
        m21.setVisible(true);
    }//GEN-LAST:event_tmj21ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "\n"+"Aplikasi Routine Kasir v.1.0" + "\n" + "\n" + "Code By : JotiiGanteng" + "\n" + "Email : Prajuritn@gmail.com" + "\n" + "WA : 082365882321" + "\n" + "Copyright : 2019-2020" + "\n" + "Lisensi Berbayar Dilarang MengCopy-Paste    " + "\n" + "\n");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conk = DriverManager.getConnection("jdbc:mysql://localhost:3306/routine" , "root" , "");
            sttk = conk.createStatement();
            JOptionPane.showMessageDialog(null,"Koneksi Aktif");
            statm.setText("AKTIF");
            statm.setForeground(Color.green);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            statm.setText("TIDAK AKTIF");
            statm.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        penjualan m1 = new penjualan();
        m1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel statm;
    public javax.swing.JButton tmj1;
    private javax.swing.JButton tmj10;
    private javax.swing.JButton tmj11;
    private javax.swing.JButton tmj12;
    private javax.swing.JButton tmj13;
    private javax.swing.JButton tmj14;
    private javax.swing.JButton tmj15;
    private javax.swing.JButton tmj16;
    private javax.swing.JButton tmj17;
    private javax.swing.JButton tmj18;
    private javax.swing.JButton tmj19;
    private javax.swing.JButton tmj2;
    private javax.swing.JButton tmj20;
    private javax.swing.JButton tmj21;
    private javax.swing.JButton tmj3;
    private javax.swing.JButton tmj4;
    private javax.swing.JButton tmj5;
    private javax.swing.JButton tmj6;
    private javax.swing.JButton tmj7;
    private javax.swing.JButton tmj8;
    private javax.swing.JButton tmj9;
    // End of variables declaration//GEN-END:variables
}
